# Plugin Configuration

# Prefix for all plugin messages
Prefix: '&c&lQueue &8&l> &7'

# Queue messages with placeholders
Queue_Messages:
  Queue_Added: '&7You have successfully joined the queue at position &c#%position%&7 of &c%maxpos%&7!'
  Queue_Move: '&7Your position in the queue is now &c#%position%&7 out of &c%maxpos%&7!'
  Queue_Done: '&aYou have left the queue and will be redirected to a server!'

# List of servers that have queues enabled
Servers:
  - 'Bedwars'
  - 'Skywars'
  - 'Practice'

# Permission required to bypass the queue
Bypass_Perm: 'queue.bypass'

# Sound to play when a player joins the queue
Join_Queue_Sound: 'entity.player.levelup' # Example sound

# Sound to play when a player leaves the queue
Leave_Queue_Sound: 'entity.player.death' # Example sound

# Message to show when the queue is full
Queue_Full: '&cThe queue is currently full. Please try again later!'

# Whether to notify players of their position in the queue
Notify_Position_Change: true

# Message to display while waiting
Wait_Time_Message: '&7You are in the queue. Please wait...'

# Whether the server is in maintenance mode
Maintenance_Mode: false

# Maximum size of the queue
Max_Queue_Size: 100
