name: SwiftQueueServer
version: '1.0-SNAPSHOT'
main: xyz.swift.swiftqueueserver.SwiftQueueServer
api-version: '1.13'
description: A lightweight server designed for extreme player counts by removing a large majority of functionality
authors:
  - Druva
  - Jonawoningsp


commands:
  queue:
    description: Manage the queue system
    usage: /<command> <join|leave> [server]
  system:
    description: Manage the queue system settings
    usage: /<command> <on|off>
permissions:
  queue.use:
    description: Allows using the queue command
    default: true
  queue.system:
    description: Allows managing the queue system
    default: op
